# Generated by Django 2.0.1 on 2018-04-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyLog',
            fields=[
                ('userID', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('exerciseName', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('caloriesPerMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('foodName', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='logHasExercise',
            fields=[
                ('exerciseName', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('userID', models.IntegerField(primary_key=True)),
                ('minsExercised', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='logHasFood',
            fields=[
                ('foodName', models.CharField(max_length=75, primary_key=True)),
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=75)),
                ('lastName', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
    ]
