# Generated by Django 2.0.4 on 2018-04-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caloriecounter', '0002_auto_20180426_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghasexercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loghasfood',
            name='user',
        ),
        migrations.AddField(
            model_name='loghasexercise',
            name='dailyLog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caloriecounter.DailyLog'),
        ),
        migrations.AddField(
            model_name='loghasfood',
            name='dailyLog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caloriecounter.DailyLog'),
        ),
    ]
